"use client";

import { AnimatePresence, motion } from "framer-motion";
import { X, Sparkles, Copy } from "lucide-react";
import ReactMarkdown from "react-markdown";
import Swal from "sweetalert2";

interface AICareerCoachModalProps {
  open: boolean;
  onClose: () => void;
  suggestion: string;
}

export default function AICareerCoachModal({
  open,
  onClose,
  suggestion,
}: AICareerCoachModalProps) {
  const handleCopy = async () => {
    await navigator.clipboard.writeText(suggestion);

    Swal.fire({
      icon: "success",
      title: "Copied!",
      text: "AI suggestion copied to clipboard.",
      timer: 1500,
      showConfirmButton: false,
      background: document.documentElement.classList.contains("dark")
        ? "#111827"
        : "#ffffff",
      color: document.documentElement.classList.contains("dark")
        ? "#fff"
        : "#111",
    });
  };

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-md p-4"
        >
          <motion.div
            initial={{
              opacity: 0,
              y: 40,
              scale: 0.95,
            }}
            animate={{
              opacity: 1,
              y: 0,
              scale: 1,
            }}
            exit={{
              opacity: 0,
              y: 40,
              scale: 0.95,
            }}
            transition={{
              duration: 0.25,
            }}
            className="
              relative
              flex
              max-h-[90vh]
              w-full
              max-w-5xl
              flex-col
              overflow-hidden
              rounded-3xl
              border
              border-gray-200/70
              bg-white
              shadow-2xl
              dark:border-gray-700
              dark:bg-gray-900
            "
          >
            {/* Header */}

            <div
              className="
                flex
                items-center
                justify-between
                border-b
                border-gray-200
                bg-gray-50/80
                px-7
                py-5
                dark:border-gray-700
                dark:bg-gray-800/70
              "
            >
              <div className="flex items-center gap-4">
                <div
                  className="
                    flex
                    h-14
                    w-14
                    items-center
                    justify-center
                    rounded-2xl
                    bg-gradient-to-r
                    from-cyan-500
                    via-indigo-600
                    to-violet-600
                    text-white
                    shadow-lg
                  "
                >
                  <Sparkles size={26} />
                </div>

                <div>
                  <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
                    AI Career Coach
                  </h2>

                  <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                    Personalized career advice generated by AI
                  </p>
                </div>
              </div>

              <button
                onClick={onClose}
                className="
                  rounded-xl
                  p-2.5
                  text-gray-500
                  transition
                  hover:bg-gray-200
                  hover:text-gray-900
                  dark:text-gray-400
                  dark:hover:bg-gray-700
                  dark:hover:text-white
                "
              >
                <X size={22} />
              </button>
            </div>

            {/* Content */}

            <div
              className="
                flex-1
                overflow-y-auto
                px-8
                py-7
                text-gray-700
                dark:text-gray-300
                prose
                prose-gray
                dark:prose-invert
                max-w-none

                prose-headings:text-gray-900
                dark:prose-headings:text-white

                prose-strong:text-indigo-600
                dark:prose-strong:text-cyan-400

                prose-code:text-pink-600
                dark:prose-code:text-pink-400

                prose-a:text-indigo-600
                dark:prose-a:text-cyan-400

                prose-li:marker:text-indigo-500
              "
            >
              <ReactMarkdown>{suggestion}</ReactMarkdown>
            </div>

            {/* Footer */}

            <div
              className="
                flex
                items-center
                justify-end
                gap-3
                border-t
                border-gray-200
                bg-gray-50/70
                px-7
                py-5
                dark:border-gray-700
                dark:bg-gray-800/70
              "
            >
              <button
                onClick={handleCopy}
                className="
                  inline-flex
                  items-center
                  gap-2
                  rounded-xl
                  border
                  border-gray-300
                  bg-white
                  px-5
                  py-2.5
                  font-medium
                  text-gray-700
                  transition
                  hover:bg-gray-100
                  dark:border-gray-600
                  dark:bg-gray-900
                  dark:text-gray-200
                  dark:hover:bg-gray-800
                "
              >
                <Copy size={18} />
                Copy
              </button>

              <button
                onClick={onClose}
                className="
                  rounded-xl
                  bg-gradient-to-r
                  from-cyan-500
                  via-indigo-600
                  to-violet-600
                  px-6
                  py-2.5
                  font-semibold
                  text-white
                  shadow-lg
                  transition
                  hover:scale-[1.02]
                  active:scale-95
                "
              >
                Close
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
